; Listing generated by Microsoft (R) Optimizing Compiler Version 19.11.25508.2 

	TITLE	C:\Users\pierr\Documents\UQAC\Cours\Intelligence artificielle pour le jeu vidéo - 8IAR125\IA\source projet IA\Buckland_Chapter7 to 10_Raven\goals\Goal_SayPhrase.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

END
